language: java
jdk:
 - oraclejdk8
install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
 - mysql
before_install:
 - mysql -e 'CREATE DATABASE cve;'
 - cp src/test/java/application.test.properties src/main/resources/application.properties
script:
 - mvn test
after_success:
 - bash <(curl -s https://codecov.io/bash)