language: java
jdk:
 - oraclejdk8
test:
  adapter: mysql2
  database: cve
  username: travis
  encoding: utf8
install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
 - mysql
before_install:
 - mysql -e 'CREATE DATABASE cve;'
script:
 - mvn test
after_success:
 - bash <(curl -s https://codecov.io/bash)